### ISSUE TITLE
playback speed control is hidden and not functioning

### ISSUE THREAD

**Issue by propertunist** [nicetip/videojs-speed#1]
when i run this plugin, there is no visible effect on the video player.
i disabled css value of 'display:none' for the playback button via the browser inspector and i could then see the playback speed button rendered on the player.
yet when i click the number '1' that is now visible on the player, i see a blue triangle above the number and no other possible options.
what did i miss here?
thanks

**Comment by Hussnain1** [comment]
I need the speed button in latest version of video.js
Do you have this?

**Comment by nicetip** [comment]
I just updated. Now, videojs-speed module supports video-js-4.6.3 version.
video-js changed internally. 
Try again with sample code and let me know other problem if you find.

**Comment by Hussnain1** [comment]
Okay. Do you have HD toggle button version of video.js?
