### ISSUE TITLE
No support for VideoJS 5.4.4?

### ISSUE THREAD

**Issue by hanfeisun** [nicetip/videojs-speed#4]
When I use the example code of videojs-speed, it throws an error which says it can't find `MenuItem` under `videojs`

**Comment by nicetip** [comment]
Yes, it does not support recent versions of VideoJS.
Now, VideoJS support playbackrate features.
you can implement that like this way.
good luck.

HTML:

```
        <video id="session_video" class="video-js vjs-default-skin">
        <source src="{src}"  type="{type}">
        </video>
```

javascript:

var videoOptions = {
     controls: true, autoplay: true, preload: true, width: '100%', height: '100%',
     playbackRates: [1, 2, 4, 8],
     controlBar: { muteToggle: false, volumeControl: false }
};
var player = videojs(document.getElementById('session_video'), videoOptions, function() {
    // callback
});

**Comment by hanfeisun** [comment]
Got it. Thanks a lot!
